// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2S.Api.Data;

#nullable disable

namespace P2S.Api.Data.Migrations
{
    [DbContext(typeof(P2SDbContext))]
    partial class P2SDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("P2S.Api.Data.Entities.Cancellation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ReimbursementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ReimbursementId");

                    b.ToTable("Cancellations");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.DailyFinanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OpenCancellationsCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalInventoryValueToday")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOrderedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalReimbursementPending")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("DailyFinanceSnapshots");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchMethod")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ScannedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ScannedCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ScannedByUserId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.InventoryWithdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("WithdrawalReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WithdrawnAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WithdrawnByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("WithdrawalReasonId");

                    b.HasIndex("WithdrawnByUserId");

                    b.ToTable("InventoryWithdrawals");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Courier")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNo")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TrackingNo");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SP",
                            IsActive = true,
                            Name = "Shopee"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TT",
                            IsActive = true,
                            Name = "TikTok Shop"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AM",
                            IsActive = true,
                            Name = "Amazon/Lazada"
                        });
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SkuCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<string>("PlatformOrderNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderedByUserId");

                    b.HasIndex("PlatformId", "PlatformOrderNo");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Reimbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Reimbursements");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.StaffLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int?>("RelatedCancellationId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedPurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedReimbursementId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedCancellationId");

                    b.HasIndex("RelatedPurchaseOrderId");

                    b.HasIndex("RelatedReimbursementId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffLedgerEntries");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$6.ODqcZJThUh843qWE0.Wu6pN6xlwY8S9hg88ttf5AT1O.EhomOz.",
                            RoleId = 3,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.WithdrawalReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "ขาย"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "ชำรุด"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "โอนย้าย"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "อื่นๆ"
                        });
                });

            modelBuilder.Entity("PurchaseOrderReimbursement", b =>
                {
                    b.Property<int>("PurchaseOrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseOrdersId", "ReimbursementId");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("PurchaseOrderReimbursement");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Cancellation", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.OrderItem", "OrderItem")
                        .WithOne("Cancellation")
                        .HasForeignKey("P2S.Api.Data.Entities.Cancellation", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.Reimbursement", "Reimbursement")
                        .WithMany("Cancellations")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrderItem");

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Delivery", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.OrderItem", "OrderItem")
                        .WithOne("Delivery")
                        .HasForeignKey("P2S.Api.Data.Entities.Delivery", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.User", "ScannedByUser")
                        .WithMany()
                        .HasForeignKey("ScannedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("ScannedByUser");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.OrderItem", "OrderItem")
                        .WithOne("InventoryItem")
                        .HasForeignKey("P2S.Api.Data.Entities.InventoryItem", "OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.Product", "Product")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.InventoryWithdrawal", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.InventoryItem", "InventoryItem")
                        .WithMany("Withdrawals")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.WithdrawalReason", "WithdrawalReason")
                        .WithMany()
                        .HasForeignKey("WithdrawalReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.User", "WithdrawnByUser")
                        .WithMany()
                        .HasForeignKey("WithdrawnByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("WithdrawalReason");

                    b.Navigation("WithdrawnByUser");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.User", "OrderedByUser")
                        .WithMany()
                        .HasForeignKey("OrderedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderedByUser");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Reimbursement", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.StaffLedgerEntry", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.Cancellation", "RelatedCancellation")
                        .WithMany("StaffLedgerEntries")
                        .HasForeignKey("RelatedCancellationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("P2S.Api.Data.Entities.PurchaseOrder", "RelatedPurchaseOrder")
                        .WithMany("StaffLedgerEntries")
                        .HasForeignKey("RelatedPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("P2S.Api.Data.Entities.Reimbursement", "RelatedReimbursement")
                        .WithMany("StaffLedgerEntries")
                        .HasForeignKey("RelatedReimbursementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("P2S.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedCancellation");

                    b.Navigation("RelatedPurchaseOrder");

                    b.Navigation("RelatedReimbursement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.User", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PurchaseOrderReimbursement", b =>
                {
                    b.HasOne("P2S.Api.Data.Entities.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2S.Api.Data.Entities.Reimbursement", null)
                        .WithMany()
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Cancellation", b =>
                {
                    b.Navigation("StaffLedgerEntries");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.InventoryItem", b =>
                {
                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.OrderItem", b =>
                {
                    b.Navigation("Cancellation");

                    b.Navigation("Delivery");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Product", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("StaffLedgerEntries");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Reimbursement", b =>
                {
                    b.Navigation("Cancellations");

                    b.Navigation("StaffLedgerEntries");
                });

            modelBuilder.Entity("P2S.Api.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
